name: Actualizar EPG Filtrada

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de filtrado
        run: python filter_epg.py

      - name: Subir cambios al repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg_reducida.xml
          git commit -m "Actualización automática de EPG" || exit 0
          git push
