name: Limpieza Profunda de Historial

on:
  schedule:
    - cron: '0 0 */3 * *' # Se ejecuta cada 3 días automáticamente
  workflow_dispatch: # Para lanzarlo manualmente cuando quieras

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Borrar todas las ejecuciones antiguas
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0      # Borra todo lo que tenga más de 0 días de antigüedad
          keep_minimum_runs: 1 # Mantiene únicamente la última ejecución exitosa de respaldo por workflow
