name: Actualizador Diario de EPG

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta todos los días a las 00:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde la web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar Script de Filtro
        run: python filter_epg.py

      - name: Subir cambios a GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add guia_personalizada.xml guia_personalizada.xml.gz
          git commit -m "Actualización automática de EPG (XML y GZ)" || exit 0
          git push
