name: Actualizar EPG Filtrada

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3. Instalar librerías
        run: |
          pip install requests
          # No necesitamos pytz si usamos el método de datetime puro que te daré abajo

      - name: 4. Ejecutar script de filtrado y shift
        run: python filter_epg.py

      - name: 5. Guardar y subir cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Añadimos los resultados. El shift.txt no se añade aquí porque tú lo editas manual.
          git add epg_reducida.xml epg_reducida.xml.gz errores_canales.txt
          
          if git diff --staged --quiet; then
            echo "Sin cambios en la EPG."
          else
            git commit -m "EPG Actualizada con Shift: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
