name: Actualizar EPG Filtrada

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente cada medianoche (hora UTC)
  workflow_dispatch:      # Permite ejecución manual desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permisos necesarios para que el robot pueda escribir en tu repositorio
    permissions:
      contents: write

    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3. Instalar librerías necesarias
        run: pip install requests

      - name: 4. Ejecutar el script de filtrado y detección de errores
        run: python filter_epg.py

      - name: 5. Guardar y subir los cambios (EPG + Log de Errores)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Añadimos la EPG generada y el reporte de canales no encontrados
          git add epg_reducida.xml errores_canales.txt
          
          # Verificamos si hay cambios reales para evitar commits vacíos
          if git diff --staged --quiet; then
            echo "No hay cambios detectados en la EPG ni en los errores."
          else
            git commit -m "Actualización automática EPG: $(date +'%Y-%m-%d %H:%M')"
            git push
          
          fi
